import { Roles } from './roles';

export enum Permissions {
  GENERATE_REPORT = 'GENERATE_REPORT',
  VIEW_SUBJECTS = 'VIEW_SUBJECTS',
  VIEW_OWN_REPORTS = 'VIEW_OWN_REPORTS',
  
  REVIEW_REPORT = 'REVIEW_REPORT',
  REJECT_REPORT = 'REJECT_REPORT',
  APPROVE_REPORT = 'APPROVE_REPORT',

  MANAGE_FACULTY = 'MANAGE_FACULTY',
  MANAGE_SUBJECTS = 'MANAGE_SUBJECTS',
  ASSIGN_FACULTY = 'ASSIGN_FACULTY',
  PUBLISH_REPORTS = 'PUBLISH_REPORTS',

  VIEW_DASHBOARD = 'VIEW_DASHBOARD',
  VIEW_ANALYTICS = 'VIEW_ANALYTICS',
  DOWNLOAD_REPORTS = 'DOWNLOAD_REPORTS',

  // Admin Module Permissions
  ADMIN_DASHBOARD_VIEW = 'ADMIN_DASHBOARD_VIEW',
  CO_VIEW = 'CO_VIEW',
  CO_UPLOAD = 'CO_UPLOAD',
  CO_CREATE = 'CO_CREATE',
  CO_UPDATE = 'CO_UPDATE',
  CO_DELETE = 'CO_DELETE',
  SUBJECT_VIEW = 'SUBJECT_VIEW',
  SUBJECT_CREATE = 'SUBJECT_CREATE',
  SUBJECT_UPDATE = 'SUBJECT_UPDATE',
  SUBJECT_DELETE = 'SUBJECT_DELETE',
  FACULTY_VIEW = 'FACULTY_VIEW',
  FACULTY_UPLOAD = 'FACULTY_UPLOAD',
  FACULTY_CREATE = 'FACULTY_CREATE',
  FACULTY_UPDATE = 'FACULTY_UPDATE',
  FACULTY_LOCK = 'FACULTY_LOCK',
  FACULTY_UNLOCK = 'FACULTY_UNLOCK',
  FACULTY_ASSIGNMENT_VIEW = 'FACULTY_ASSIGNMENT_VIEW',
  FACULTY_ASSIGNMENT_CREATE = 'FACULTY_ASSIGNMENT_CREATE',
  FACULTY_ASSIGNMENT_UPDATE = 'FACULTY_ASSIGNMENT_UPDATE',
  FACULTY_ASSIGNMENT_DELETE = 'FACULTY_ASSIGNMENT_DELETE',
  ATTAINMENT_CONFIG_VIEW = 'ATTAINMENT_CONFIG_VIEW',
  ATTAINMENT_CONFIG_UPDATE = 'ATTAINMENT_CONFIG_UPDATE',
  MANAGE_SURVEYS = 'MANAGE_SURVEYS'
}

export const RolePermissions: Record<Roles, Permissions[]> = {
  [Roles.FACULTY]: [
    Permissions.GENERATE_REPORT,
    Permissions.VIEW_SUBJECTS,
    Permissions.VIEW_OWN_REPORTS
  ],
  [Roles.COORDINATOR]: [
    Permissions.REVIEW_REPORT,
    Permissions.REJECT_REPORT,
    Permissions.APPROVE_REPORT,
    Permissions.VIEW_SUBJECTS
  ],
  [Roles.ADMIN]: [
    Permissions.MANAGE_FACULTY,
    Permissions.MANAGE_SUBJECTS,
    Permissions.ASSIGN_FACULTY,
    Permissions.PUBLISH_REPORTS,
    Permissions.VIEW_DASHBOARD,
    
    // Review Workflow (Shared with Coordinator)
    Permissions.REVIEW_REPORT,
    Permissions.REJECT_REPORT,
    Permissions.APPROVE_REPORT,
    
    // Admin Module Permissions
    Permissions.ADMIN_DASHBOARD_VIEW,
    Permissions.CO_VIEW,
    Permissions.CO_UPLOAD,
    Permissions.CO_CREATE,
    Permissions.CO_UPDATE,
    Permissions.CO_DELETE,
    Permissions.SUBJECT_VIEW,
    Permissions.SUBJECT_CREATE,
    Permissions.SUBJECT_UPDATE,
    Permissions.SUBJECT_DELETE,
    Permissions.FACULTY_VIEW,
    Permissions.FACULTY_UPLOAD,
    Permissions.FACULTY_CREATE,
    Permissions.FACULTY_UPDATE,
    Permissions.FACULTY_LOCK,
    Permissions.FACULTY_UNLOCK,
    Permissions.FACULTY_ASSIGNMENT_VIEW,
    Permissions.FACULTY_ASSIGNMENT_CREATE,
    Permissions.FACULTY_ASSIGNMENT_UPDATE,
    Permissions.FACULTY_ASSIGNMENT_DELETE,
    Permissions.ATTAINMENT_CONFIG_VIEW,
    Permissions.ATTAINMENT_CONFIG_UPDATE,
    Permissions.MANAGE_SURVEYS
  ],
  [Roles.MANAGEMENT]: [
    Permissions.VIEW_DASHBOARD,
    Permissions.VIEW_ANALYTICS,
    Permissions.DOWNLOAD_REPORTS
  ]
};
