export enum ReportStatus {
  DRAFT = 'DRAFT',
  GENERATED = 'GENERATED',
  SUBMITTED = 'SUBMITTED',
  REVIEWED = 'REVIEWED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PUBLISHED = 'PUBLISHED',
}

export enum ReportType {
  INTERNAL = 'INTERNAL',
  EXTERNAL = 'EXTERNAL',
  OVERALL = 'OVERALL',
  INDIRECT = 'INDIRECT',
  COPO = 'COPO',
}
